spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_logistic_department?currentSchema=logistic
    username: postgres
    password: admin
  jpa:
    database: postgresql
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: logistic
